name: TBConsult
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.17.0
  flutter_dotenv: ^6.0.1
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.2
  speech_to_text: ^7.3.0
  google_fonts: ^8.1.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  http: ^1.2.1
  flutter_markdown: ^0.7.7+1
  dio: ^5.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/knowledge/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

